# 11. For example, if we give 9119 the function should return 811181, as the square of 9 is 81 and square
# of 1 is 1.



# list="9119"
# i=0
# while i<len(list):
#     b=int(list[i])**2
#     i=i+1
#     print(b,end="")

# list=[9,1,1,9]
# i=0
# s=[]
# while i<len(list):
#     s.append(list[i]**2)
#     i=i+1
# print(s)

# list=[9,1,1,9]
# i=0
# s=""
# while i<len(list):
#     s=s+(str(list[i]**2))
#     i=i+1
# print(s)

# l=[9,1,1,9]
# i=0
# while i<len(l):
#     a=(l[i]**2)
#     i=i+1
#     print(a,end="")


# a=[]
# size=int(input("enter the size of list"))
# for i in range(size):
#     val=int(input("enter numbers"))
#     a.append(val)
#     i=0
# while i<len(a):
#     b=(a[i])**2
#     i=i+1
#     print(b,end="")
