# 42. Write a Python program to iterate a given list cyclically on specific index position.
# Original list:
# ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']
# Iterate the said list cyclically on specific index position 3 :
# ['d', 'e', 'f', 'g', 'h', 'a', 'b', 'c']
# Iterate the said list cyclically on specific index position 5 :
# ['f', 'g', 'h', 'a', 'b', 'c', 'd', 'e']

# n=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']
# print(n[3:]+n[:3])
# print(n[5:]+n[:5])


