# 45.
# Write a Python program to remove the last N number of elements from a given list.
# Original lists:
# [2, 3, 9, 8, 2, 0, 39, 84, 2, 2, 34, 2, 34, 5, 3, 5]
# Remove the last 3 elements from the said list:
# [2, 3, 9, 8, 2, 0, 39, 84, 2, 2, 34, 2, 34]
# Remove the last 5 elements from the said list:
# [2, 3, 9, 8, 2, 0, 39, 84, 2, 2, 34]
# Remove the last 1 element from the said list:
# [2, 3, 9, 8, 2, 0, 39, 84, 2, 2, 34, 2, 34, 5, 3]

# a=[3,5,4,6,7,8,9,2,4,3]
# b=len(a)
# i=6
# while i>0:
#     i=i-1
#     print(a[i],end=",")



n=[2, 3, 9, 8, 2, 0, 39, 84, 2, 2, 34, 2, 34, 5, 3, 5]
print(n[:-3])
print(n[:-5])
print(n[:-1])

