# Count unique values inside a list.
# input_list = [1, 2, 2, 5, 8, 4, 4, 8]
# Count = 5 #because [1,2,5,8,4] are unique values.


# a=[1,2,2,5,8,4,4,8]
# p=[]
# i=0
# count=0
# while i<len(a):
#     if a[i] not in p:
#         p.append(a[i])
#         count=count+1
#     i=i+1
# print(p)
# print(count)

# l=[1,2,2,5,8,4,4,8]
# a=[]
# i=0
# c=0
# while i<len(l):
#     if l[i] not in a:
#         a.append(l[i])
#         c=c+1
#     i=i+1
# print(c)