##append:-

# a=[1,2,3,4]
# a.append(6)
# print(a)

# a=[1,2,3,4]
# a.append("jaya")
# print(a)

## clear:-
# a=[1,2,3,4]
# a.clear()
# print(a)

##copy():-
# a=[1,2,3,4,5]
# a.copy()
# print(a)

## count:-
# a=[1,2,3,4,5,5]
# b=a.count(5)
# print(b) #ek varible lekr hi hoga

## extend:-
# a=[1,2,3,4,5]
# b=["jaya","aarti","bulbul","anjali"]
# a.extend(b)
# print(a)

# a=[1,2,3,4,5]
# b=["jaya","aarti","bulbul","anjali"]
# b.extend(a)
# print(b)

# a=[1,2,3,45,6]
# a.extend(["jaya","aarti"])
# print(a)


# index:-
# a=[1,2,4,5,6]
# b=a.index(2)
# print(b)  #ek variable lekr hi hoga

# insert:-
# a=[1,2,3,4,5,6]
# a.insert(1,"jaya")
# print(a)     #[1,"jaya",2,3,4,5,6]

# pop:-
# a=[1,2,3,4,5]
# a.pop()
# print(a)

# a=[1,2,3,4,5]
# a.pop(1)
# print(a)

# remove:-
# a=[1,2,3,4,5,9]
# a.remove(5)
# print(a) 
   

# reverse:-
# a=[1,2,3,4,5,6,7,8,9]
# a.reverse()
# print(a)

# a=["jaya","chiku","aarti","twinkle"]
# a.reverse()
# print(a)

# sort:-
# a=[1,7,9,5,3,8,6,0]
# a.sort()
# print(a)  #aarohi kram/badtek kram

# a=["jaya","chiku","twinkle","aarti"]
# a.sort()
# print(a)

# a=["jaya","chiku","aarti","twinkle"]
# a.sort(reverse=False)
# print(a)

# a=[1,2,3,6,9,0,4,3]
# a.sort(reverse=False)
# print(a)

# a=[1,6,9,4,2,9,0]
# a.sort(reverse=True)
# print(a)

# a=["aarti","twinkle","jaya","chiku"]
# a.sort(reverse=True)
# print(a)



##del/delete:-
# a=[1,3,6,8,0,4]
# del a[2]
# print(a)

# by slicing:-
# a=[11,22,33,44]
# del a[1:]
# print(a)

# a=[11,22,33,44,55,66]
# del a[2:4]
# print(a)

# len(:-)
# a=[1,2,3,4,5,67,9]
# b=len(a)
# print(b)

# a=[1,2,3,4,5,6,7,8]
# print(len(a))

# list:-
# a="hello"
# b=list(a)
# print(b)

# a="helllo"
# print(list(a))


# min:-
# a=[1,4,8,0,6,54]
# b=min(a)
# print(b)

# a=[1,2,3,4,5]
# print(min(a))

# sum():-
# a=[1,1,1,1,1,1]
# b=sum(a)
# print(b)

# a=[1,1,1,1,1,1]
# print(sum(a))

# split:-
# a="hello-how-are-you"
# b=a.split("-")
# print(b)

# a="hello how are you"
# b=a.split(" ")
# print(b)

# join:-
# a=["jaya","kumawat","aarti","twinkle"]
# b="-".join(a)
# print(b)





